// ROOT VIEW
export const ROOT_CHANGE_CATEGORY = 'ROOT_CHANGE_CATEGORY';
export const ROOT_LIST_CATEGORIES = 'ROOT_LIST_CATEGORIES';
export const ROOT_LIST_POSTS = 'ROOT_LIST_POSTS';
export const ROOT_UPDATE_POSTS = 'ROOT_UPDATE_POSTS';
export const ROOT_SHOW_POST = 'ROOT_SHOW_POST';
export const ROOT_DIALOG_POST_FORM = 'ROOT_DIALOG_POST_FORM';

// POST FORM VIEW
export const POST_HANDLE_CHANGE = 'POST_HANDLE_CHANGE';
export const POST_CHANGE_CATEGORY = 'POST_CHANGE_CATEGORY';
export const POST_FORM_SAVE = 'POST_FORM_SAVE';
export const POST_VALID_FORM = 'POST_VALID_FORM';
export const POST_CLEAN_FORM = 'POST_CLEAN_FORM';