// ROOT VIEW
export const ROOT_CHANGE_CATEGORY = 'ROOT_CHANGE_CATEGORY';
export const ROOT_LIST_CATEGORIES = 'ROOT_LIST_CATEGORIES';
export const ROOT_LIST_POSTS = 'ROOT_LIST_POSTS';
export const ROOT_SHOW_POST = 'ROOT_SHOW_POST';
export const ROOT_ADD_NEW_POST = 'ROOT_ADD_NEW_POST';